export const locations = [
	{
		clinic: "Banjara Hills Clinic",
		area: "Banjara Hills",
		location: "Near Lake View, Banjara Hills",
		state: "Karnataka",
		pincode: "500122",
	},
	{
		clinic: "Miyapur Clinic",
		area: "Miyapur",
		location: "Adjacent to Hospital, Miyapur",
		state: "Telangana",
		pincode: "500103",
	},
	{
		clinic: "LB Nagar Clinic",
		area: "LB Nagar",
		location: "Near Metro Station, LB Nagar",
		state: "Tamil Nadu",
		pincode: "500166",
	},
	{
		clinic: "Banjara Hills Clinic",
		area: "Banjara Hills",
		location: "Adjacent to Hospital, Banjara Hills",
		state: "Karnataka",
		pincode: "500198",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Near Metro Station, Kompally",
		state: "Karnataka",
		pincode: "500014",
	},
	{
		clinic: "Secunderabad Clinic",
		area: "Secunderabad",
		location: "Opp. Community Center, Secunderabad",
		state: "Andhra Pradesh",
		pincode: "500113",
	},
	{
		clinic: "Uppal Clinic",
		area: "Uppal",
		location: "Close to Mall, Uppal",
		state: "Tamil Nadu",
		pincode: "500060",
	},
	{
		clinic: "Gachibowli Clinic",
		area: "Gachibowli",
		location: "Adjacent to Hospital, Gachibowli",
		state: "Andhra Pradesh",
		pincode: "500113",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Close to Mall, Kompally",
		state: "Karnataka",
		pincode: "500148",
	},
	{
		clinic: "Secunderabad Clinic",
		area: "Secunderabad",
		location: "Beside Main Road, Secunderabad",
		state: "Tamil Nadu",
		pincode: "500043",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Beside Main Road, Kompally",
		state: "Telangana",
		pincode: "500059",
	},
	{
		clinic: "Ameerpet Clinic",
		area: "Ameerpet",
		location: "Near Metro Station, Ameerpet",
		state: "Telangana",
		pincode: "500196",
	},
	{
		clinic: "Miyapur Clinic",
		area: "Miyapur",
		location: "Near Metro Station, Miyapur",
		state: "Tamil Nadu",
		pincode: "500101",
	},
	{
		clinic: "Mehdipatnam Clinic",
		area: "Mehdipatnam",
		location: "Adjacent to Hospital, Mehdipatnam",
		state: "Telangana",
		pincode: "500098",
	},
	{
		clinic: "LB Nagar Clinic",
		area: "LB Nagar",
		location: "Adjacent to Hospital, LB Nagar",
		state: "Karnataka",
		pincode: "500060",
	},
	{
		clinic: "Uppal Clinic",
		area: "Uppal",
		location: "Next to Park, Uppal",
		state: "Andhra Pradesh",
		pincode: "500036",
	},
	{
		clinic: "Uppal Clinic",
		area: "Uppal",
		location: "Next to Park, Uppal",
		state: "Tamil Nadu",
		pincode: "500101",
	},
	{
		clinic: "Mehdipatnam Clinic",
		area: "Mehdipatnam",
		location: "Near Lake View, Mehdipatnam",
		state: "Andhra Pradesh",
		pincode: "500165",
	},
	{
		clinic: "Mehdipatnam Clinic",
		area: "Mehdipatnam",
		location: "Next to Park, Mehdipatnam",
		state: "Andhra Pradesh",
		pincode: "500022",
	},
	{
		clinic: "Ameerpet Clinic",
		area: "Ameerpet",
		location: "Close to Mall, Ameerpet",
		state: "Karnataka",
		pincode: "500176",
	},
	{
		clinic: "Banjara Hills Clinic",
		area: "Banjara Hills",
		location: "Near Lake View, Banjara Hills",
		state: "Telangana",
		pincode: "500035",
	},
	{
		clinic: "Ameerpet Clinic",
		area: "Ameerpet",
		location: "Close to Mall, Ameerpet",
		state: "Andhra Pradesh",
		pincode: "500027",
	},
	{
		clinic: "Mehdipatnam Clinic",
		area: "Mehdipatnam",
		location: "Near Lake View, Mehdipatnam",
		state: "Telangana",
		pincode: "500076",
	},
	{
		clinic: "Uppal Clinic",
		area: "Uppal",
		location: "Near Bus Stop, Uppal",
		state: "Telangana",
		pincode: "500063",
	},
	{
		clinic: "Ameerpet Clinic",
		area: "Ameerpet",
		location: "Opp. Community Center, Ameerpet",
		state: "Tamil Nadu",
		pincode: "500085",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Opp. Community Center, Kompally",
		state: "Karnataka",
		pincode: "500200",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Behind School, Kompally",
		state: "Tamil Nadu",
		pincode: "500020",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Adjacent to Hospital, Kompally",
		state: "Andhra Pradesh",
		pincode: "500178",
	},
	{
		clinic: "Banjara Hills Clinic",
		area: "Banjara Hills",
		location: "Opposite Police Station, Banjara Hills",
		state: "Tamil Nadu",
		pincode: "500032",
	},
	{
		clinic: "Gachibowli Clinic",
		area: "Gachibowli",
		location: "Near Lake View, Gachibowli",
		state: "Karnataka",
		pincode: "500165",
	},
	{
		clinic: "Gachibowli Clinic",
		area: "Gachibowli",
		location: "Opposite Police Station, Gachibowli",
		state: "Tamil Nadu",
		pincode: "500134",
	},
	{
		clinic: "Mehdipatnam Clinic",
		area: "Mehdipatnam",
		location: "Opposite Police Station, Mehdipatnam",
		state: "Andhra Pradesh",
		pincode: "500192",
	},
	{
		clinic: "Miyapur Clinic",
		area: "Miyapur",
		location: "Close to Mall, Miyapur",
		state: "Tamil Nadu",
		pincode: "500030",
	},
	{
		clinic: "Miyapur Clinic",
		area: "Miyapur",
		location: "Close to Mall, Miyapur",
		state: "Karnataka",
		pincode: "500009",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Next to Park, Kompally",
		state: "Karnataka",
		pincode: "500084",
	},
	{
		clinic: "LB Nagar Clinic",
		area: "LB Nagar",
		location: "Behind School, LB Nagar",
		state: "Andhra Pradesh",
		pincode: "500158",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Next to Park, Kompally",
		state: "Telangana",
		pincode: "500113",
	},
	{
		clinic: "Kukatpally Clinic",
		area: "Kukatpally",
		location: "Next to Park, Kukatpally",
		state: "Karnataka",
		pincode: "500184",
	},
	{
		clinic: "Gachibowli Clinic",
		area: "Gachibowli",
		location: "Beside Main Road, Gachibowli",
		state: "Karnataka",
		pincode: "500007",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Adjacent to Hospital, Kompally",
		state: "Telangana",
		pincode: "500023",
	},
	{
		clinic: "Banjara Hills Clinic",
		area: "Banjara Hills",
		location: "Close to Mall, Banjara Hills",
		state: "Andhra Pradesh",
		pincode: "500190",
	},
	{
		clinic: "Ameerpet Clinic",
		area: "Ameerpet",
		location: "Next to Park, Ameerpet",
		state: "Telangana",
		pincode: "500030",
	},
	{
		clinic: "Secunderabad Clinic",
		area: "Secunderabad",
		location: "Near Lake View, Secunderabad",
		state: "Karnataka",
		pincode: "500020",
	},
	{
		clinic: "Mehdipatnam Clinic",
		area: "Mehdipatnam",
		location: "Next to Park, Mehdipatnam",
		state: "Tamil Nadu",
		pincode: "500072",
	},
	{
		clinic: "Uppal Clinic",
		area: "Uppal",
		location: "Behind School, Uppal",
		state: "Andhra Pradesh",
		pincode: "500133",
	},
	{
		clinic: "Kukatpally Clinic",
		area: "Kukatpally",
		location: "Near Metro Station, Kukatpally",
		state: "Telangana",
		pincode: "500117",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Beside Main Road, Kompally",
		state: "Telangana",
		pincode: "500038",
	},
	{
		clinic: "Miyapur Clinic",
		area: "Miyapur",
		location: "Adjacent to Hospital, Miyapur",
		state: "Tamil Nadu",
		pincode: "500032",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Near Metro Station, Kompally",
		state: "Karnataka",
		pincode: "500133",
	},
	{
		clinic: "LB Nagar Clinic",
		area: "LB Nagar",
		location: "Beside Main Road, LB Nagar",
		state: "Telangana",
		pincode: "500142",
	},
	{
		clinic: "Gachibowli Clinic",
		area: "Gachibowli",
		location: "Opposite Police Station, Gachibowli",
		state: "Andhra Pradesh",
		pincode: "500144",
	},
	{
		clinic: "Ameerpet Clinic",
		area: "Ameerpet",
		location: "Next to Park, Ameerpet",
		state: "Karnataka",
		pincode: "500068",
	},
	{
		clinic: "Banjara Hills Clinic",
		area: "Banjara Hills",
		location: "Opp. Community Center, Banjara Hills",
		state: "Karnataka",
		pincode: "500121",
	},
	{
		clinic: "LB Nagar Clinic",
		area: "LB Nagar",
		location: "Opp. Community Center, LB Nagar",
		state: "Telangana",
		pincode: "500148",
	},
	{
		clinic: "Secunderabad Clinic",
		area: "Secunderabad",
		location: "Adjacent to Hospital, Secunderabad",
		state: "Andhra Pradesh",
		pincode: "500175",
	},
	{
		clinic: "Kukatpally Clinic",
		area: "Kukatpally",
		location: "Next to Park, Kukatpally",
		state: "Andhra Pradesh",
		pincode: "500042",
	},
	{
		clinic: "Kukatpally Clinic",
		area: "Kukatpally",
		location: "Close to Mall, Kukatpally",
		state: "Karnataka",
		pincode: "500071",
	},
	{
		clinic: "Kukatpally Clinic",
		area: "Kukatpally",
		location: "Beside Main Road, Kukatpally",
		state: "Telangana",
		pincode: "500098",
	},
	{
		clinic: "Banjara Hills Clinic",
		area: "Banjara Hills",
		location: "Next to Park, Banjara Hills",
		state: "Andhra Pradesh",
		pincode: "500056",
	},
	{
		clinic: "Gachibowli Clinic",
		area: "Gachibowli",
		location: "Near Lake View, Gachibowli",
		state: "Karnataka",
		pincode: "500040",
	},
	{
		clinic: "Secunderabad Clinic",
		area: "Secunderabad",
		location: "Close to Mall, Secunderabad",
		state: "Andhra Pradesh",
		pincode: "500077",
	},
	{
		clinic: "Miyapur Clinic",
		area: "Miyapur",
		location: "Beside Main Road, Miyapur",
		state: "Tamil Nadu",
		pincode: "500155",
	},
	{
		clinic: "Miyapur Clinic",
		area: "Miyapur",
		location: "Adjacent to Hospital, Miyapur",
		state: "Telangana",
		pincode: "500128",
	},
	{
		clinic: "Miyapur Clinic",
		area: "Miyapur",
		location: "Near Metro Station, Miyapur",
		state: "Andhra Pradesh",
		pincode: "500109",
	},
	{
		clinic: "Gachibowli Clinic",
		area: "Gachibowli",
		location: "Near Bus Stop, Gachibowli",
		state: "Andhra Pradesh",
		pincode: "500161",
	},
	{
		clinic: "LB Nagar Clinic",
		area: "LB Nagar",
		location: "Next to Park, LB Nagar",
		state: "Karnataka",
		pincode: "500079",
	},
	{
		clinic: "Banjara Hills Clinic",
		area: "Banjara Hills",
		location: "Near Bus Stop, Banjara Hills",
		state: "Andhra Pradesh",
		pincode: "500095",
	},
	{
		clinic: "Banjara Hills Clinic",
		area: "Banjara Hills",
		location: "Opposite Police Station, Banjara Hills",
		state: "Telangana",
		pincode: "500022",
	},
	{
		clinic: "Mehdipatnam Clinic",
		area: "Mehdipatnam",
		location: "Close to Mall, Mehdipatnam",
		state: "Karnataka",
		pincode: "500161",
	},
	{
		clinic: "Mehdipatnam Clinic",
		area: "Mehdipatnam",
		location: "Close to Mall, Mehdipatnam",
		state: "Andhra Pradesh",
		pincode: "500180",
	},
	{
		clinic: "Kukatpally Clinic",
		area: "Kukatpally",
		location: "Near Lake View, Kukatpally",
		state: "Telangana",
		pincode: "500168",
	},
	{
		clinic: "Mehdipatnam Clinic",
		area: "Mehdipatnam",
		location: "Close to Mall, Mehdipatnam",
		state: "Karnataka",
		pincode: "500173",
	},
	{
		clinic: "LB Nagar Clinic",
		area: "LB Nagar",
		location: "Adjacent to Hospital, LB Nagar",
		state: "Andhra Pradesh",
		pincode: "500079",
	},
	{
		clinic: "Secunderabad Clinic",
		area: "Secunderabad",
		location: "Beside Main Road, Secunderabad",
		state: "Karnataka",
		pincode: "500131",
	},
	{
		clinic: "Secunderabad Clinic",
		area: "Secunderabad",
		location: "Opposite Police Station, Secunderabad",
		state: "Telangana",
		pincode: "500185",
	},
	{
		clinic: "LB Nagar Clinic",
		area: "LB Nagar",
		location: "Adjacent to Hospital, LB Nagar",
		state: "Tamil Nadu",
		pincode: "500068",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Near Metro Station, Kompally",
		state: "Andhra Pradesh",
		pincode: "500187",
	},
	{
		clinic: "Banjara Hills Clinic",
		area: "Banjara Hills",
		location: "Near Bus Stop, Banjara Hills",
		state: "Andhra Pradesh",
		pincode: "500059",
	},
	{
		clinic: "Ameerpet Clinic",
		area: "Ameerpet",
		location: "Near Lake View, Ameerpet",
		state: "Andhra Pradesh",
		pincode: "500163",
	},
	{
		clinic: "Secunderabad Clinic",
		area: "Secunderabad",
		location: "Adjacent to Hospital, Secunderabad",
		state: "Tamil Nadu",
		pincode: "500135",
	},
	{
		clinic: "Miyapur Clinic",
		area: "Miyapur",
		location: "Next to Park, Miyapur",
		state: "Karnataka",
		pincode: "500026",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Near Lake View, Kompally",
		state: "Telangana",
		pincode: "500126",
	},
	{
		clinic: "Miyapur Clinic",
		area: "Miyapur",
		location: "Near Metro Station, Miyapur",
		state: "Andhra Pradesh",
		pincode: "500110",
	},
	{
		clinic: "LB Nagar Clinic",
		area: "LB Nagar",
		location: "Near Metro Station, LB Nagar",
		state: "Andhra Pradesh",
		pincode: "500122",
	},
	{
		clinic: "Gachibowli Clinic",
		area: "Gachibowli",
		location: "Beside Main Road, Gachibowli",
		state: "Karnataka",
		pincode: "500085",
	},
	{
		clinic: "Gachibowli Clinic",
		area: "Gachibowli",
		location: "Behind School, Gachibowli",
		state: "Karnataka",
		pincode: "500042",
	},
	{
		clinic: "Ameerpet Clinic",
		area: "Ameerpet",
		location: "Opposite Police Station, Ameerpet",
		state: "Karnataka",
		pincode: "500011",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Near Metro Station, Kompally",
		state: "Tamil Nadu",
		pincode: "500118",
	},
	{
		clinic: "Secunderabad Clinic",
		area: "Secunderabad",
		location: "Opposite Police Station, Secunderabad",
		state: "Tamil Nadu",
		pincode: "500163",
	},
	{
		clinic: "Gachibowli Clinic",
		area: "Gachibowli",
		location: "Near Lake View, Gachibowli",
		state: "Tamil Nadu",
		pincode: "500068",
	},
	{
		clinic: "Secunderabad Clinic",
		area: "Secunderabad",
		location: "Adjacent to Hospital, Secunderabad",
		state: "Telangana",
		pincode: "500182",
	},
	{
		clinic: "Banjara Hills Clinic",
		area: "Banjara Hills",
		location: "Behind School, Banjara Hills",
		state: "Tamil Nadu",
		pincode: "500048",
	},
	{
		clinic: "Ameerpet Clinic",
		area: "Ameerpet",
		location: "Close to Mall, Ameerpet",
		state: "Telangana",
		pincode: "500138",
	},
	{
		clinic: "Gachibowli Clinic",
		area: "Gachibowli",
		location: "Opp. Community Center, Gachibowli",
		state: "Telangana",
		pincode: "500019",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Opp. Community Center, Kompally",
		state: "Telangana",
		pincode: "500130",
	},
	{
		clinic: "Banjara Hills Clinic",
		area: "Banjara Hills",
		location: "Near Lake View, Banjara Hills",
		state: "Telangana",
		pincode: "500140",
	},
	{
		clinic: "Banjara Hills Clinic",
		area: "Banjara Hills",
		location: "Close to Mall, Banjara Hills",
		state: "Tamil Nadu",
		pincode: "500016",
	},
	{
		clinic: "Gachibowli Clinic",
		area: "Gachibowli",
		location: "Near Metro Station, Gachibowli",
		state: "Andhra Pradesh",
		pincode: "500030",
	},
	{
		clinic: "Secunderabad Clinic",
		area: "Secunderabad",
		location: "Opposite Police Station, Secunderabad",
		state: "Telangana",
		pincode: "500165",
	},
	{
		clinic: "Mehdipatnam Clinic",
		area: "Mehdipatnam",
		location: "Close to Mall, Mehdipatnam",
		state: "Telangana",
		pincode: "500117",
	},
	{
		clinic: "Miyapur Clinic",
		area: "Miyapur",
		location: "Near Bus Stop, Miyapur",
		state: "Andhra Pradesh",
		pincode: "500059",
	},
	{
		clinic: "Ameerpet Clinic",
		area: "Ameerpet",
		location: "Opp. Community Center, Ameerpet",
		state: "Telangana",
		pincode: "500179",
	},
	{
		clinic: "Kukatpally Clinic",
		area: "Kukatpally",
		location: "Beside Main Road, Kukatpally",
		state: "Andhra Pradesh",
		pincode: "500005",
	},
	{
		clinic: "Miyapur Clinic",
		area: "Miyapur",
		location: "Opposite Police Station, Miyapur",
		state: "Tamil Nadu",
		pincode: "500117",
	},
	{
		clinic: "Mehdipatnam Clinic",
		area: "Mehdipatnam",
		location: "Opp. Community Center, Mehdipatnam",
		state: "Tamil Nadu",
		pincode: "500183",
	},
	{
		clinic: "Uppal Clinic",
		area: "Uppal",
		location: "Near Metro Station, Uppal",
		state: "Telangana",
		pincode: "500107",
	},
	{
		clinic: "Secunderabad Clinic",
		area: "Secunderabad",
		location: "Near Lake View, Secunderabad",
		state: "Andhra Pradesh",
		pincode: "500059",
	},
	{
		clinic: "Ameerpet Clinic",
		area: "Ameerpet",
		location: "Beside Main Road, Ameerpet",
		state: "Tamil Nadu",
		pincode: "500188",
	},
	{
		clinic: "Banjara Hills Clinic",
		area: "Banjara Hills",
		location: "Close to Mall, Banjara Hills",
		state: "Karnataka",
		pincode: "500119",
	},
	{
		clinic: "Banjara Hills Clinic",
		area: "Banjara Hills",
		location: "Opp. Community Center, Banjara Hills",
		state: "Karnataka",
		pincode: "500067",
	},
	{
		clinic: "Gachibowli Clinic",
		area: "Gachibowli",
		location: "Opposite Police Station, Gachibowli",
		state: "Tamil Nadu",
		pincode: "500119",
	},
	{
		clinic: "Banjara Hills Clinic",
		area: "Banjara Hills",
		location: "Near Bus Stop, Banjara Hills",
		state: "Telangana",
		pincode: "500027",
	},
	{
		clinic: "Mehdipatnam Clinic",
		area: "Mehdipatnam",
		location: "Next to Park, Mehdipatnam",
		state: "Karnataka",
		pincode: "500012",
	},
	{
		clinic: "Mehdipatnam Clinic",
		area: "Mehdipatnam",
		location: "Opposite Police Station, Mehdipatnam",
		state: "Karnataka",
		pincode: "500019",
	},
	{
		clinic: "Ameerpet Clinic",
		area: "Ameerpet",
		location: "Adjacent to Hospital, Ameerpet",
		state: "Andhra Pradesh",
		pincode: "500032",
	},
	{
		clinic: "Mehdipatnam Clinic",
		area: "Mehdipatnam",
		location: "Near Lake View, Mehdipatnam",
		state: "Karnataka",
		pincode: "500033",
	},
	{
		clinic: "Secunderabad Clinic",
		area: "Secunderabad",
		location: "Near Lake View, Secunderabad",
		state: "Karnataka",
		pincode: "500016",
	},
	{
		clinic: "Ameerpet Clinic",
		area: "Ameerpet",
		location: "Close to Mall, Ameerpet",
		state: "Andhra Pradesh",
		pincode: "500042",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Near Metro Station, Kompally",
		state: "Telangana",
		pincode: "500122",
	},
	{
		clinic: "Ameerpet Clinic",
		area: "Ameerpet",
		location: "Behind School, Ameerpet",
		state: "Telangana",
		pincode: "500163",
	},
	{
		clinic: "Secunderabad Clinic",
		area: "Secunderabad",
		location: "Next to Park, Secunderabad",
		state: "Karnataka",
		pincode: "500028",
	},
	{
		clinic: "Uppal Clinic",
		area: "Uppal",
		location: "Next to Park, Uppal",
		state: "Telangana",
		pincode: "500159",
	},
	{
		clinic: "Secunderabad Clinic",
		area: "Secunderabad",
		location: "Next to Park, Secunderabad",
		state: "Telangana",
		pincode: "500132",
	},
	{
		clinic: "Miyapur Clinic",
		area: "Miyapur",
		location: "Opp. Community Center, Miyapur",
		state: "Tamil Nadu",
		pincode: "500046",
	},
	{
		clinic: "Secunderabad Clinic",
		area: "Secunderabad",
		location: "Next to Park, Secunderabad",
		state: "Andhra Pradesh",
		pincode: "500021",
	},
	{
		clinic: "Uppal Clinic",
		area: "Uppal",
		location: "Adjacent to Hospital, Uppal",
		state: "Karnataka",
		pincode: "500055",
	},
	{
		clinic: "Mehdipatnam Clinic",
		area: "Mehdipatnam",
		location: "Opposite Police Station, Mehdipatnam",
		state: "Karnataka",
		pincode: "500139",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Behind School, Kompally",
		state: "Telangana",
		pincode: "500094",
	},
	{
		clinic: "Gachibowli Clinic",
		area: "Gachibowli",
		location: "Near Lake View, Gachibowli",
		state: "Tamil Nadu",
		pincode: "500027",
	},
	{
		clinic: "Mehdipatnam Clinic",
		area: "Mehdipatnam",
		location: "Adjacent to Hospital, Mehdipatnam",
		state: "Andhra Pradesh",
		pincode: "500069",
	},
	{
		clinic: "Kukatpally Clinic",
		area: "Kukatpally",
		location: "Next to Park, Kukatpally",
		state: "Telangana",
		pincode: "500168",
	},
	{
		clinic: "LB Nagar Clinic",
		area: "LB Nagar",
		location: "Beside Main Road, LB Nagar",
		state: "Andhra Pradesh",
		pincode: "500200",
	},
	{
		clinic: "Ameerpet Clinic",
		area: "Ameerpet",
		location: "Next to Park, Ameerpet",
		state: "Tamil Nadu",
		pincode: "500184",
	},
	{
		clinic: "Mehdipatnam Clinic",
		area: "Mehdipatnam",
		location: "Beside Main Road, Mehdipatnam",
		state: "Karnataka",
		pincode: "500137",
	},
	{
		clinic: "Uppal Clinic",
		area: "Uppal",
		location: "Next to Park, Uppal",
		state: "Karnataka",
		pincode: "500164",
	},
	{
		clinic: "Uppal Clinic",
		area: "Uppal",
		location: "Near Metro Station, Uppal",
		state: "Karnataka",
		pincode: "500010",
	},
	{
		clinic: "Uppal Clinic",
		area: "Uppal",
		location: "Near Metro Station, Uppal",
		state: "Tamil Nadu",
		pincode: "500165",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Near Metro Station, Kompally",
		state: "Karnataka",
		pincode: "500179",
	},
	{
		clinic: "Gachibowli Clinic",
		area: "Gachibowli",
		location: "Behind School, Gachibowli",
		state: "Karnataka",
		pincode: "500122",
	},
	{
		clinic: "Uppal Clinic",
		area: "Uppal",
		location: "Behind School, Uppal",
		state: "Andhra Pradesh",
		pincode: "500081",
	},
	{
		clinic: "LB Nagar Clinic",
		area: "LB Nagar",
		location: "Beside Main Road, LB Nagar",
		state: "Andhra Pradesh",
		pincode: "500168",
	},
	{
		clinic: "Gachibowli Clinic",
		area: "Gachibowli",
		location: "Opposite Police Station, Gachibowli",
		state: "Tamil Nadu",
		pincode: "500034",
	},
	{
		clinic: "Mehdipatnam Clinic",
		area: "Mehdipatnam",
		location: "Behind School, Mehdipatnam",
		state: "Andhra Pradesh",
		pincode: "500153",
	},
	{
		clinic: "Uppal Clinic",
		area: "Uppal",
		location: "Close to Mall, Uppal",
		state: "Tamil Nadu",
		pincode: "500178",
	},
	{
		clinic: "Secunderabad Clinic",
		area: "Secunderabad",
		location: "Behind School, Secunderabad",
		state: "Andhra Pradesh",
		pincode: "500119",
	},
	{
		clinic: "Uppal Clinic",
		area: "Uppal",
		location: "Behind School, Uppal",
		state: "Karnataka",
		pincode: "500026",
	},
	{
		clinic: "Uppal Clinic",
		area: "Uppal",
		location: "Opp. Community Center, Uppal",
		state: "Andhra Pradesh",
		pincode: "500191",
	},
	{
		clinic: "Miyapur Clinic",
		area: "Miyapur",
		location: "Opposite Police Station, Miyapur",
		state: "Andhra Pradesh",
		pincode: "500122",
	},
	{
		clinic: "Kukatpally Clinic",
		area: "Kukatpally",
		location: "Close to Mall, Kukatpally",
		state: "Karnataka",
		pincode: "500182",
	},
	{
		clinic: "Gachibowli Clinic",
		area: "Gachibowli",
		location: "Opp. Community Center, Gachibowli",
		state: "Telangana",
		pincode: "500116",
	},
	{
		clinic: "Ameerpet Clinic",
		area: "Ameerpet",
		location: "Beside Main Road, Ameerpet",
		state: "Karnataka",
		pincode: "500075",
	},
	{
		clinic: "LB Nagar Clinic",
		area: "LB Nagar",
		location: "Opp. Community Center, LB Nagar",
		state: "Tamil Nadu",
		pincode: "500151",
	},
	{
		clinic: "Mehdipatnam Clinic",
		area: "Mehdipatnam",
		location: "Opp. Community Center, Mehdipatnam",
		state: "Andhra Pradesh",
		pincode: "500023",
	},
	{
		clinic: "LB Nagar Clinic",
		area: "LB Nagar",
		location: "Adjacent to Hospital, LB Nagar",
		state: "Telangana",
		pincode: "500081",
	},
	{
		clinic: "LB Nagar Clinic",
		area: "LB Nagar",
		location: "Beside Main Road, LB Nagar",
		state: "Telangana",
		pincode: "500044",
	},
	{
		clinic: "Uppal Clinic",
		area: "Uppal",
		location: "Behind School, Uppal",
		state: "Tamil Nadu",
		pincode: "500150",
	},
	{
		clinic: "Secunderabad Clinic",
		area: "Secunderabad",
		location: "Beside Main Road, Secunderabad",
		state: "Telangana",
		pincode: "500037",
	},
	{
		clinic: "Miyapur Clinic",
		area: "Miyapur",
		location: "Opposite Police Station, Miyapur",
		state: "Karnataka",
		pincode: "500154",
	},
	{
		clinic: "LB Nagar Clinic",
		area: "LB Nagar",
		location: "Next to Park, LB Nagar",
		state: "Telangana",
		pincode: "500147",
	},
	{
		clinic: "Uppal Clinic",
		area: "Uppal",
		location: "Opposite Police Station, Uppal",
		state: "Andhra Pradesh",
		pincode: "500197",
	},
	{
		clinic: "Gachibowli Clinic",
		area: "Gachibowli",
		location: "Near Lake View, Gachibowli",
		state: "Telangana",
		pincode: "500066",
	},
	{
		clinic: "Secunderabad Clinic",
		area: "Secunderabad",
		location: "Adjacent to Hospital, Secunderabad",
		state: "Karnataka",
		pincode: "500075",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Opposite Police Station, Kompally",
		state: "Telangana",
		pincode: "500199",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Opp. Community Center, Kompally",
		state: "Karnataka",
		pincode: "500069",
	},
	{
		clinic: "Uppal Clinic",
		area: "Uppal",
		location: "Next to Park, Uppal",
		state: "Andhra Pradesh",
		pincode: "500108",
	},
	{
		clinic: "Miyapur Clinic",
		area: "Miyapur",
		location: "Adjacent to Hospital, Miyapur",
		state: "Telangana",
		pincode: "500055",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Behind School, Kompally",
		state: "Karnataka",
		pincode: "500169",
	},
	{
		clinic: "Miyapur Clinic",
		area: "Miyapur",
		location: "Adjacent to Hospital, Miyapur",
		state: "Tamil Nadu",
		pincode: "500026",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Behind School, Kompally",
		state: "Tamil Nadu",
		pincode: "500132",
	},
	{
		clinic: "Uppal Clinic",
		area: "Uppal",
		location: "Opposite Police Station, Uppal",
		state: "Tamil Nadu",
		pincode: "500200",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Next to Park, Kompally",
		state: "Andhra Pradesh",
		pincode: "500132",
	},
	{
		clinic: "Secunderabad Clinic",
		area: "Secunderabad",
		location: "Next to Park, Secunderabad",
		state: "Telangana",
		pincode: "500138",
	},
	{
		clinic: "Banjara Hills Clinic",
		area: "Banjara Hills",
		location: "Close to Mall, Banjara Hills",
		state: "Karnataka",
		pincode: "500194",
	},
	{
		clinic: "Mehdipatnam Clinic",
		area: "Mehdipatnam",
		location: "Beside Main Road, Mehdipatnam",
		state: "Andhra Pradesh",
		pincode: "500165",
	},
	{
		clinic: "Gachibowli Clinic",
		area: "Gachibowli",
		location: "Adjacent to Hospital, Gachibowli",
		state: "Tamil Nadu",
		pincode: "500138",
	},
	{
		clinic: "Ameerpet Clinic",
		area: "Ameerpet",
		location: "Close to Mall, Ameerpet",
		state: "Karnataka",
		pincode: "500087",
	},
	{
		clinic: "Secunderabad Clinic",
		area: "Secunderabad",
		location: "Near Metro Station, Secunderabad",
		state: "Andhra Pradesh",
		pincode: "500016",
	},
	{
		clinic: "Ameerpet Clinic",
		area: "Ameerpet",
		location: "Near Lake View, Ameerpet",
		state: "Tamil Nadu",
		pincode: "500197",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Near Lake View, Kompally",
		state: "Karnataka",
		pincode: "500157",
	},
	{
		clinic: "Uppal Clinic",
		area: "Uppal",
		location: "Opposite Police Station, Uppal",
		state: "Tamil Nadu",
		pincode: "500196",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Opposite Police Station, Kompally",
		state: "Telangana",
		pincode: "500019",
	},
	{
		clinic: "Mehdipatnam Clinic",
		area: "Mehdipatnam",
		location: "Opposite Police Station, Mehdipatnam",
		state: "Karnataka",
		pincode: "500107",
	},
	{
		clinic: "Uppal Clinic",
		area: "Uppal",
		location: "Opp. Community Center, Uppal",
		state: "Telangana",
		pincode: "500087",
	},
	{
		clinic: "LB Nagar Clinic",
		area: "LB Nagar",
		location: "Opp. Community Center, LB Nagar",
		state: "Tamil Nadu",
		pincode: "500020",
	},
	{
		clinic: "Kompally Clinic",
		area: "Kompally",
		location: "Adjacent to Hospital, Kompally",
		state: "Telangana",
		pincode: "500159",
	},
];
