name: Archive Backers

on:
    schedule:
        - cron: "0 0 */1 * *" # Every 1 days at 00:00 UTC
    workflow_dispatch:

jobs:
    run-script:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install script dependencies
              run: |
                  npm install @supabase/supabase-js dotenv node-telegram-bot-api razorpay

            - name: Run archival script
              run: node scripts/archive-backers.mjs
              env:
                  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
                  SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
                  TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
                  TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
                  RAZORPAY_KEY_ID: ${{ secrets.RAZORPAY_KEY_ID }}
                  RAZORPAY_KEY_SECRET: ${{ secrets.RAZORPAY_KEY_SECRET }}
